CREATE DATABASE tindas;

USE tindas;

CREATE TABLE IF NOT EXISTS `categories` (
  `ID_CAT` int(11) NOT NULL,
  `LABEL_CAT` varchar(55) NOT NULL,
  PRIMARY KEY (`ID_CAT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `matchs` (
  `ID_USR` int(11) NOT NULL,
  `ID_TOURN` int(11) NOT NULL,
  `NB_PTS` int(11) NOT NULL,
  KEY `ID_USR` (`ID_USR`,`ID_TOURN`),
  KEY `ID_TOURN` (`ID_TOURN`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `tournois` (
  `ID_TOURN` int(11) NOT NULL AUTO_INCREMENT,
  `DATEDEB_TOURN` datetime NOT NULL,
  `DATEFIN_TOURN` datetime NOT NULL,
  PRIMARY KEY (`ID_TOURN`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `users` (
  `ID_USR` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_USR` varchar(55) NOT NULL,
  `FIRSTNAME_USR` varchar(55) NOT NULL,
  `AGE_USR` int(11) NOT NULL,
  `MAIL_USR` varchar(100) NOT NULL,
  `CAT_USR` int(11) NOT NULL,
  PRIMARY KEY (`ID_USR`),
  KEY `CAT_USR` (`CAT_USR`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


ALTER TABLE `matchs`
  ADD CONSTRAINT `matchs_tournois` FOREIGN KEY (`ID_TOURN`) REFERENCES `tournois` (`ID_TOURN`),
  ADD CONSTRAINT `matchs_users` FOREIGN KEY (`ID_USR`) REFERENCES `users` (`ID_USR`);

ALTER TABLE `users`
  ADD CONSTRAINT `categorie_user` FOREIGN KEY (`CAT_USR`) REFERENCES `categories` (`ID_CAT`);

